services:
  postgres:
    image: postgres:18-alpine
    container_name: gorest-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${GOREST_DATABASE_USER}
      POSTGRES_PASSWORD: ${GOREST_DATABASE_PASSWORD}
      POSTGRES_DB: ${GOREST_DATABASE_NAME}

    ports:
      - "${GOREST_DATABASE_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${GOREST_DATABASE_USER} -d ${GOREST_DATABASE_NAME}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  
  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: gorest-api
    restart: unless-stopped

    environment:
      GOREST_APP_ENVIRONMENT: development
      GOREST_SERVER_HOST: 0.0.0.0
      GOREST_SERVER_PORT: 8080

      GOREST_DATABASE_HOST: postgres
      GOREST_DATABASE_PORT: 5432
      GOREST_DATABASE_USER: ${GOREST_DATABASE_USER}
      GOREST_DATABASE_PASSWORD: ${GOREST_DATABASE_PASSWORD}
      GOREST_DATABASE_NAME: ${GOREST_DATABASE_NAME}
      GOREST_DATABASE_SSL_MODE: disable

      GOREST_AUTH_ACCESS_TOKEN_SECRET: ${GOREST_AUTH_ACCESS_TOKEN_SECRET}
      GOREST_AUTH_REFRESH_TOKEN_SECRET: ${GOREST_AUTH_REFRESH_TOKEN_SECRET}

      GOREST_LOGGER_LEVEL: debug
      GOREST_LOGGER_FORMAT: json
      GOREST_LOGGER_ADD_SOURCE: "true"

    ports:
      - "${GOREST_SERVER_PORT}:8080"

    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
